name: IkarisGPT Auto-Describe-Issue

on:
  issues:
    types:
      - labeled

jobs:
  AutoDescribe:
    if: github.event.label.name == 'auto-described'
    runs-on: ubuntu-latest
    name: IkarisGPT Auto Describe Issue
    steps:
      - name: IkarisGPT Action Step
        id: ikaris
        uses: devAyushDubey/Ikaris-GPT@v1.0.0-beta
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
      # Use the output from the `hello` step
      - name: Get the output message
        run: echo "${{ steps.ikaris.outputs.message }}"
